name: python app

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read 

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                pytho-versions: ["3.7","3.8","3.9"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up python ${{matrix.pytho-versions}}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.pytho-versions }}

            - name: Install Requirements

              run: | 
                python -m pip install --upgrade pip
                pip install flake8 pytest tox tox-gh-actions
                pip install -r requirements.txt

            - name: Test with tox
              run: tox

        